apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniprojecte-deployment
  labels:
    app: MiniProject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MiniProject 
  template:
    metadata:
      labels:
        app: MiniProject
    spec:
      containers:
      - name: miniproject
        image: subscriptioncr.azurecr.io/subfinalinstance:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: mailorderpharmacyvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: miniprojecteevc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MiniProject
